apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: nginx-php
  name: nginx-config
data:
  nginx.conf: |-
    worker_processes 1;
    error_log  /var/log/nginx/error.log warn;
    pid        /tmp/nginx.pid;
    load_module modules/ngx_http_geoip2_module.so;
    events {
        worker_connections  1024;
    }
    http {
        client_body_temp_path /tmp/client_temp;
        proxy_temp_path       /tmp/proxy_temp_path;
        fastcgi_temp_path     /tmp/fastcgi_temp;
        uwsgi_temp_path       /tmp/uwsgi_temp;
        scgi_temp_path        /tmp/scgi_temp;

        set_real_ip_from 127.0.0.1;
        set_real_ip_from 10.0.0.0/8;
        set_real_ip_from 172.16.0.0/12;
        set_real_ip_from 192.168.0.0/16;

        real_ip_header    X-Forwarded-For;
        real_ip_recursive on;
        
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        #tcp_nopush     on;
        keepalive_timeout  65;
        #gzip  on;
        server {
            listen       8080;
            root         /var/www/html;
            location ~ ^(.+\.php)(.*)$
            {
             
                include fastcgi_params;
                # fastcgi_param SCRIPT_FILENAME $document_root/index.php;
                add_header X-Instance $hostname always;
                fastcgi_split_path_info       ^(.+\.php)(.*)$;
                fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
                fastcgi_param PATH_INFO       $fastcgi_path_info;
                fastcgi_pass unix:/phpsocket/php-fpm.sock;
            }
        }
    }