###########################################
### Deployment
###########################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: nginx-php
  name: nginx-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-php
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-php
    spec:                     
      containers:
        # Nginx
        - image: registry.npohosting.nl/npohosting/nginx:1.25
          imagePullPolicy: Always
          name: nginx
          command:
            - /usr/libexec/s2i/run
          ports:
            - containerPort: 9000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 10Mi
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config
              subPath: nginx.conf
              readOnly: true                                 
            - mountPath: /phpsocket
              name: phpsocket
            - mountPath: /var/www/html
              name: docroot
        # php-fpm
        - image: registry.npohosting.nl/npohosting/php-fpm:8.2
          imagePullPolicy: Always
          name: php-fpm
          command:
            - /usr/libexec/s2i/run       
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 10Mi
          volumeMounts:
            - mountPath: /usr/local/etc/php-fpm.d
              name: php-fpm-config              
            - mountPath: /phpsocket
              name: phpsocket              
            - mountPath: /var/www/html
              name: docroot              
      restartPolicy: Always
      securityContext: {}
      volumes: 
        - name: phpsocket
          emptyDir: {}
        - name: docroot
          emptyDir: {}
        - name: nginx-config
          configMap:
            defaultMode: 420
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf                  
        - name: php-fpm-config
          configMap:
            defaultMode: 420
            name: php-fpm-config             
