apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: nginx-php
  name: nginx-php
spec:
  ports:
  - name: nginx
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: nginx-php
  sessionAffinity: None
  type: ClusterIP