apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: __NAME__
  namespace: traefik
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`__HOSTNAME__`)
    priority: 10
    services:
    - kind: Service
      name: __SERVICENAME__
      namespace: __NAMESPACE__
      port: __PORT__
      responseForwarding:
        flushInterval: 1ms
      scheme: http
      strategy: RoundRobin
      weight: 10
  tls:
    secretName: __TLSSECRET__